### ISSUE TITLE
Failed to start web server

### ISSUE THREAD

**Issue by Kisamij** [guldkage/Pterodactyl-Installer#12]
× nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-05-09 17:49:26 CEST; 6min ago
       Docs: man:nginx(8)
    Process: 18705 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 34ms

May 09 17:49:26 luomo systemd[1]: Starting A high performance web server and a reverse proxy server...
May 09 17:49:26 luomo nginx[18705]: nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/panel.xxxx.xx/fullchain.pem":>
May 09 17:49:26 luomo nginx[18705]: nginx: configuration file /etc/nginx/nginx.conf test failed
May 09 17:49:26 luomo systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May 09 17:49:26 luomo systemd[1]: nginx.service: Failed with result 'exit-code'.
May 09 17:49:26 luomo systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by guldkage** [comment]
Hello

Sorry for the late answer. I have notifications on, but I somehow still dont get notifications.
certbot failed to issue a certificate for your domain - this can be because of port 80 not being open, or that you did not create an A record for your panel.

**Comment by guldkage** [comment]
Hello

Typically 502 in this scenario is caused by php fpm not running
Try to run "systemctl enable php8.1-fpm --now"

**Comment by Kisamij** [comment]
"Failed to enable unit: Unit file php8.1-fpm.service does not exist."

i tried the command but it told me not exist

**Comment by Adib23704** [comment]
Try using php -v and see which php version you have installed.

**Comment by Kisamij** [comment]
"
php -v
Command 'php' not found, but can be installed with:
apt install php8.1-cli  # version 8.1.2-1ubuntu2.14, or
apt install php-cli     # version 2:8.1+92ubuntu1
"
it told me i not installed it

> Try using php -v and see which php version you have installed.

**Comment by guldkage** [comment]
You will need to install php first
 apt -y install php8.1
php8.1-{cli,gd,mysql,pdo,mbstring,tokenizer,bcmath,xml,fpm,curl,zip}
If you used the script, it should have installed this itself though

**Comment by Kisamij** [comment]
i used the script but it not installed php, ty for the help <3

**Comment by guldkage** [comment]
No problem!  Glad it works
May I know what operating system you are using, so that I can look into it?

**Comment by Kisamij** [comment]
im using  ubuntu-22.04-x86_64

**Comment by guldkage** [comment]
will look into this after exams.
