### ISSUE TITLE
error

### ISSUE THREAD

**Issue by techwiz37** [guldkage/Pterodactyl-Installer#15]
![Screenshot (19)](https://github.com/guldkage/Pterodactyl-Installer/assets/73012169/1c5b0baa-47dd-4b72-a111-cf8c22c347f8)

**Comment by guldkage** [comment]
Hello
please send logs.

Panel Logs:
tail -n 150 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc pteropaste.com 99
