### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by joeymisfit** [guldkage/Pterodactyl-Installer#2]
I noticed your discord on your main github profile doesn't work anymore, did you change your discord name? As I have a few questions about the installer and I might be interested in hiring you for assistance with a project or two.

Thank you!

**Comment by guldkage** [comment]
guldkage#6208

I'm already working on a few projects, so it depends on how big the project is.
Unfortunately, I don't have enough time at the moment for a call, but write and we'll figure something out.
