### ISSUE TITLE
Pterodactyl Installer Scripts

### ISSUE THREAD

**Issue by lazy-media** [guldkage/Pterodactyl-Installer#20]
Pterodactyl states it requires PHP version 8.2 or greater. I can no longer see the Pterodactyl Panel page, instead I see this error message. This script has worked fantastically for me, many times using Ubuntu 20.04 from a fresh install. Is there anyway the version of php can be updated to 8.2 or 8.3 in these scripts? Please and thank you.

I have attached a screenshot of the error message I get.

I would edit it myself, but I don't know what needs to be changed exactly.

If you need any other information, please let me know.

![image](https://github.com/user-attachments/assets/e39c343a-63d2-477a-8d23-4f45433e7224)

**Comment by FoxXxHater** [comment]
Hey,

i have the same error. 
In my case the panel work behind a reverse proxy.

**Comment by guldkage** [comment]
Hello

I have updated the script to use PHP8.3 now.
Will do some testing with it today or tomorrow.

**Comment by FoxXxHater** [comment]
Can we run the script again? Or kill the existing system? How can we update?

**Comment by guldkage** [comment]
Running the script again would probably break something

You can install php8.3 with `apt -y install php8.3 php8.3-{cli,gd,mysql,pdo,mbstring,tokenizer,bcmath,xml,fpm,curl,zip}`
then change the PHP socket in your webserver config, for example if you use NGINX, your configuration is normally at `/etc/nginx/sites-enabled/pterodactyl.conf`

Scroll down till `location ~ \.php$ {` section and update the following line:

`fastcgi_pass unix:/run/php/php8.1-fpm.sock;`
to
`fastcgi_pass unix:/run/php/php8.3-fpm.sock;`

**Comment by FoxXxHater** [comment]
It looks like that it dont work...

![image](https://github.com/user-attachments/assets/54a2c532-cd97-4b93-a2a8-2e9128e4934d)

With http and connection refused with https

**Comment by guldkage** [comment]
I would need panel logs
tail -n 150 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc pteropaste.com 99

you will get a link, please share that

**Comment by FoxXxHater** [comment]
https://ptero.co/dimahoxuhe

**Comment by guldkage** [comment]
Your panel cannot communicate with your database, it says that it's trying to login without a password.
Maybe the script failed to setup the database, check if there is mysql credentials in `/var/www/pterodactyl/.env`

**Comment by FoxXxHater** [comment]
![image](https://github.com/user-attachments/assets/731adeda-8f88-4740-981a-04e61d3b6a59)

I didnt changed something... without the APP_URL

**Comment by guldkage** [comment]
I guess you meant you removed APP_KEY from the picture

The database creation seemed to have failed, you can set it up manually:
CREATE USER 'pterodactyl'@'127.0.0.1' IDENTIFIED BY 'somePassword';
CREATE DATABASE panel;
GRANT ALL PRIVILEGES ON panel.* TO 'pterodactyl'@'127.0.0.1';

Change "somePassword" to your own password, then update it in the .env file.

and setup your database:
php artisan migrate --seed --force

**Comment by FoxXxHater** [comment]
No i removed nothing from the picture

**Comment by guldkage** [comment]
Alright, then you also need to generate APP KEY
php artisan key:generate --force

(This will remove everything set on the panel, but as the APP KEY is not set, I would guess that you have not used the panel yet)

**Comment by FoxXxHater** [comment]
Did you updatet the script? So i kan kill my server and create a new one?

**Comment by FoxXxHater** [comment]
Okay... thats bad
Does the system runs on LXC's?

I cant create the KEY
![image](https://github.com/user-attachments/assets/f634dac7-0e82-4fe2-a35c-cbaeca4bde80)

**Comment by guldkage** [comment]
You need to be in the pterodactyl directory, cd /var/www/pterodactyl

**Comment by FoxXxHater** [comment]
I killed my mashine and create a new one

**Comment by FoxXxHater** [comment]
My reinstall worked, but my password didnt work XD

**Comment by guldkage** [comment]
Great!
You can create a new account with `cd /var/www/pterodactyl && php artisan p:user:make`

**Comment by guldkage** [comment]
Yes, that is right.
The script cannot login and create that for you since CSRF stops it from creating a session cookie to be able to create it for you.

The process has been simplified though, as you installed wings.
You only need to create a location, create a node, head to Configuration -> copy -> paste it into the server then systemctl restart wings

**Comment by FoxXxHater** [comment]
What should i enter if the wings an panel are the same server?

**Comment by guldkage** [comment]
I assume you are talking about FQDN, which you can set to your panel URL.

**Comment by lazy-media** [comment]
Script works perfectly for me. Passwords and everything get generated and applied. Panel and Wings installed successfully. I am also running this on a Proxmox VM, not LXC, in Ubuntu 20.04. I run this script directly after a fresh install of Ubuntu 20.04, even before doing an apt update and apt upgrade.
