### ISSUE TITLE
[WINGS ERROR]: Error: Configuration File Not Found

### ISSUE THREAD

**Issue by cmpdchtr** [guldkage/Pterodactyl-Installer#21]
OS: Ubuntu 20.04

[!] Panel installed.

root@aktym:~# wings

Error: Configuration File Not Found

Wings was not able to locate your configuration file, and therefore is not
able to complete its boot process. Please ensure you have copied your instance
configuration file into the default location below.

Default Location: /etc/pterodactyl/config.yml

This is not a bug with this software. Please do not make a bug report
for this issue, it will be closed.

root@aktym:~#

**Comment by guldkage** [comment]
Hello

This is not an issue with the installer.

You will still have to setup a location and node on the panel.
The script cannot do that for you.

**Comment by cmpdchtr** [comment]
Okay, I already found that in the guide. But where does the installer leave the certificates?

**Comment by guldkage** [comment]
The certificates will be stored at /etc/letsencrypt/live/<your domain>/

If you create a location, give it a name, create a node with the same FQDN as your panel (if panel & wings is on the same machine), head to "Configuration", click generate token, paste the code into SSH on your machine then systemctl restart wings, it should work just fine.

**Comment by cmpdchtr** [comment]
Ok, thanks!

**Comment by guldkage** [comment]
Let me know if it does not work :)
I marked it as completed earlier by accident.

**Comment by cmpdchtr** [comment]
I tried to enter this directory, but it simply does not exist. There is only the /etc/letsencrypt/ directory, which contains cli.ini.
Sorry for the stupid questions, I'm just new to pterodactyl

**Comment by guldkage** [comment]
No worries

If you used the installer without SSL, the directory will not exist.
You can install certbot with `apt install certbot -y`
