### ISSUE TITLE
panel not avaleble 

### ISSUE THREAD

**Issue by OfficialShinu** [guldkage/Pterodactyl-Installer#5]
can't connect to panel with the panel.domain.com and ip

**Comment by guldkage** [comment]
Hello, sorry to hear that. Can you please describe the issue in more details?

**Comment by OfficialShinu** [comment]
I used the script had no errors but can't access it in any way in browser
tried with and without cloudflare enabled (profiel disabled)

Op vr 28 apr. 2023 22:11 schreef Malthe ***@***.***>:

**Comment by guldkage** [comment]
I still need more information to help you
are the ports open on your machine, what error do you receive when you go into your panel etc?

**Comment by OfficialShinu** [comment]
Ill send you the logs in a minute
I can't  access the web panel
All Ports are open on the vps by default

Op vr 28 apr. 2023 22:34 schreef Malthe ***@***.***>:

**Comment by OfficialShinu** [comment]
the logs

***@***.***:~# tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date
+%F).log
#4
/var/www/pterodactyl/vendor/symfony/mailer/Transport/AbstractTransport.php(68):
Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doSend()
#5
/var/www/pterodactyl/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(136):
Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#6
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521):
Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->send()
#7
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(285):
Illuminate\\Mail\\Mailer->sendSymfonyMessage()
#8
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(67):
Illuminate\\Mail\\Mailer->send()
#9
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148):
Illuminate\\Notifications\\Channels\\MailChannel->send()
#10
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106):
Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#11
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19):
Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#12
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109):
Illuminate\\Notifications\\NotificationSender->withLocale()
#13
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54):
Illuminate\\Notifications\\NotificationSender->sendNow()
#14
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(104):
Illuminate\\Notifications\\ChannelManager->sendNow()
#15
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36):
Illuminate\\Notifications\\SendQueuedNotifications->handle()
#16
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(41):
Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93):
Illuminate\\Container\\Util::unwrapIfClosure()
#18
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37):
Illuminate\\Container\\BoundMethod::callBoundMethod()
#19
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(651):
Illuminate\\Container\\BoundMethod::call()
#20
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128):
Illuminate\\Container\\Container->call()
#21
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141):
Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#22
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116):
Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132):
Illuminate\\Pipeline\\Pipeline->then()
#24
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124):
Illuminate\\Bus\\Dispatcher->dispatchNow()
#25
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141):
Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#26
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116):
Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126):
Illuminate\\Pipeline\\Pipeline->then()
#28
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70):
Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#29
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98):
Illuminate\\Queue\\CallQueuedHandler->call()
#30
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425):
Illuminate\\Queue\\Jobs\\Job->fire()
#31
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375):
Illuminate\\Queue\\Worker->process()
#32
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173):
Illuminate\\Queue\\Worker->runJob()
#33
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150):
Illuminate\\Queue\\Worker->daemon()
#34
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134):
Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#35
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36):
Illuminate\\Queue\\Console\\WorkCommand->handle()
#36
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(41):
Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#37
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93):
Illuminate\\Container\\Util::unwrapIfClosure()
#38
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37):
Illuminate\\Container\\BoundMethod::callBoundMethod()
#39
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(651):
Illuminate\\Container\\BoundMethod::call()
#40
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(144):
Illuminate\\Container\\Container->call()
#41 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(291):
Illuminate\\Console\\Command->execute()
#42
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(126):
Symfony\\Component\\Console\\Command\\Command->run()
#43 /var/www/pterodactyl/vendor/symfony/console/Application.php(1002):
Illuminate\\Console\\Command->run()
#44 /var/www/pterodactyl/vendor/symfony/console/Application.php(299):
Symfony\\Component\\Console\\Application->doRunCommand()
#45 /var/www/pterodactyl/vendor/symfony/console/Application.php(171):
Symfony\\Component\\Console\\Application->doRun()
#46
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(102):
Symfony\\Component\\Console\\Application->run()
#47
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155):
Illuminate\\Console\\Application->run()
#48 /var/www/pterodactyl/artisan(37):
Illuminate\\Foundation\\Console\\Kernel->handle()
#49 {main}
"}
[2023-04-28 20:48:51] production.ERROR: Connection could not be established
with host "smtp.example.com:25": stream_socket_client():
php_network_getaddresses: getaddrinfo for smtp.example.com failed: Name or
service not known {"exception":"[object]
(Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0):
Connection could not be established with host \"smtp.example.com:25\":
stream_socket_client(): php_network_getaddresses: getaddrinfo for
smtp.example.com failed: Name or service not known at
/var/www/pterodactyl/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154)
[stacktrace]
#0 [internal function]:
Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\SocketStream->Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\{closure}()
#1
/var/www/pterodactyl/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php(157):
stream_socket_client()
#2
/var/www/pterodactyl/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(251):
Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\SocketStream->initialize()
#3
/var/www/pterodactyl/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(194):
Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->start()
#4
/var/www/pterodactyl/vendor/symfony/mailer/Transport/AbstractTransport.php(68):
Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doSend()
#5
/var/www/pterodactyl/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(136):
Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#6
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521):
Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->send()
#7
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(285):
Illuminate\\Mail\\Mailer->sendSymfonyMessage()
#8
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(67):
Illuminate\\Mail\\Mailer->send()
#9
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148):
Illuminate\\Notifications\\Channels\\MailChannel->send()
#10
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106):
Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#11
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19):
Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#12
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109):
Illuminate\\Notifications\\NotificationSender->withLocale()
#13
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54):
Illuminate\\Notifications\\NotificationSender->sendNow()
#14
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(104):
Illuminate\\Notifications\\ChannelManager->sendNow()
#15
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36):
Illuminate\\Notifications\\SendQueuedNotifications->handle()
#16
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(41):
Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93):
Illuminate\\Container\\Util::unwrapIfClosure()
#18
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37):
Illuminate\\Container\\BoundMethod::callBoundMethod()
#19
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(651):
Illuminate\\Container\\BoundMethod::call()
#20
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128):
Illuminate\\Container\\Container->call()
#21
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141):
Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#22
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116):
Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132):
Illuminate\\Pipeline\\Pipeline->then()
#24
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124):
Illuminate\\Bus\\Dispatcher->dispatchNow()
#25
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141):
Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#26
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116):
Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126):
Illuminate\\Pipeline\\Pipeline->then()
#28
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70):
Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#29
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98):
Illuminate\\Queue\\CallQueuedHandler->call()
#30
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425):
Illuminate\\Queue\\Jobs\\Job->fire()
#31
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375):
Illuminate\\Queue\\Worker->process()
#32
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173):
Illuminate\\Queue\\Worker->runJob()
#33
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150):
Illuminate\\Queue\\Worker->daemon()
#34
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134):
Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#35
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36):
Illuminate\\Queue\\Console\\WorkCommand->handle()
#36
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Util.php(41):
Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#37
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93):
Illuminate\\Container\\Util::unwrapIfClosure()
#38
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37):
Illuminate\\Container\\BoundMethod::callBoundMethod()
#39
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Container/Container.php(651):
Illuminate\\Container\\BoundMethod::call()
#40
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(144):
Illuminate\\Container\\Container->call()
#41 /var/www/pterodactyl/vendor/symfony/console/Command/Command.php(291):
Illuminate\\Console\\Command->execute()
#42
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Command.php(126):
Symfony\\Component\\Console\\Command\\Command->run()
#43 /var/www/pterodactyl/vendor/symfony/console/Application.php(1002):
Illuminate\\Console\\Command->run()
#44 /var/www/pterodactyl/vendor/symfony/console/Application.php(299):
Symfony\\Component\\Console\\Application->doRunCommand()
#45 /var/www/pterodactyl/vendor/symfony/console/Application.php(171):
Symfony\\Component\\Console\\Application->doRun()
#46
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Console/Application.php(102):
Symfony\\Component\\Console\\Application->run()
#47
/var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155):
Illuminate\\Console\\Application->run()
#48 /var/www/pterodactyl/artisan(37):
Illuminate\\Foundation\\Console\\Kernel->handle()
#49 {main}
"}

Op vr 28 apr 2023 om 22:37 schreef Shinu ***@***.***>:

**Comment by guldkage** [comment]
Those logs don't show anything useful to identifying the issue, may I know the error you get when you visit your panel?

**Comment by OfficialShinu** [comment]
ERR_CONNECTION_TIMED_OUT

site takes to long to response


[image: image.png]

Op vr 28 apr 2023 om 22:44 schreef Malthe ***@***.***>:

**Comment by guldkage** [comment]
Can you send the output of `systemctl status nginx`

**Comment by OfficialShinu** [comment]
here you go

***@***.***:~# systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor
preset: enabled)
     Active: inactive (dead) since Fri 2023-04-28 19:50:09 UTC; 1h 2min ago
       Docs: man:nginx(8)
   Main PID: 50332 (code=exited, status=0/SUCCESS)

Apr 28 19:48:51 shinu systemd[1]: Starting A high performance web server
and a reverse proxy server...
Apr 28 19:48:51 shinu systemd[1]: Started A high performance web server and
a reverse proxy server.
Apr 28 19:50:09 shinu systemd[1]: Stopping A high performance web server
and a reverse proxy server...
Apr 28 19:50:09 shinu systemd[1]: nginx.service: Succeeded.
Apr 28 19:50:09 shinu systemd[1]: Stopped A high performance web server and
a reverse proxy server.

Op vr 28 apr 2023 om 22:50 schreef Malthe ***@***.***>:

**Comment by guldkage** [comment]
Can you try typing `systemctl start nginx` and see if your panel works? If not, please type `systemctl status nginx` and send output again.

**Comment by OfficialShinu** [comment]
still nothing

***@***.***:~# systemctl start nginx
***@***.***:~# systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor
preset: enabled)
     Active: active (running) since Fri 2023-04-28 21:10:10 UTC; 1min 4s ago
       Docs: man:nginx(8)
    Process: 56405 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on;
master_process on; (code=exited, status=0/SUCCESS)
    Process: 56418 ExecStart=/usr/sbin/nginx -g daemon on; master_process
on; (code=exited, status=0/SUCCESS)
   Main PID: 56419 (nginx)
      Tasks: 5 (limit: 38495)
     Memory: 5.1M
     CGroup: /system.slice/nginx.service
             ├─56419 nginx: master process /usr/sbin/nginx -g daemon on;
master_process on;
             ├─56420 nginx: worker process
             ├─56421 nginx: worker process
             ├─56422 nginx: worker process
             └─56423 nginx: worker process

Apr 28 21:10:10 shinu systemd[1]: Starting A high performance web server
and a reverse proxy server...
Apr 28 21:10:10 shinu systemd[1]: Started A high performance web server and
a reverse proxy server.


this is what i have in cloudflare tho idk if i have something wrong here
[image: image.png]


Op vr 28 apr 2023 om 23:02 schreef Malthe ***@***.***>:

**Comment by guldkage** [comment]
Everything seems like it should, would it be possible for you to provide me with your domain name so I can check?

**Comment by OfficialShinu** [comment]
panel.shinu.site

Op vr 28 apr 2023 om 23:28 schreef Malthe ***@***.***>:

**Comment by guldkage** [comment]
I can access the panel just fine.

fre. 28. apr. 2023 23.32 skrev Shinu ***@***.***>:

**Comment by OfficialShinu** [comment]
omg found out why it din't work for me n my friends  had a pufferpanel on the same cloudflare before cleared cashe and  its working now
