### ISSUE TITLE
Doesnt Configure Nginx Correctly

### ISSUE THREAD

**Issue by jordanj334** [guldkage/Pterodactyl-Installer#6]
Nginx doesn't get configured, doesn't set server_name or add the following to the config to make SSL work 

ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;

Not sure if that's intended or not other than that great installer.

**Comment by guldkage** [comment]
I did a test installation yesterday where everything worked fine. If SSL is not included in the NGINX config, then it is because you have selected the panel without SSL.
