### ISSUE TITLE
Please add centos 7 support thank you

### ISSUE THREAD

**Issue by linkea131** [guldkage/Pterodactyl-Installer#7]
Please add centos 7 support thank you

**Comment by guldkage** [comment]
Hello linkea131

Thank you for the suggestion. I will add support for CentOS 7 in a bit.

**Comment by guldkage** [comment]
- CentOS 7 is now supported. Supported webserver is NGINX. Features available for CentOS 7: Install Panel, Install Wings, Remove Panel, Remove Wings.

Thank you for the suggestion, I will close this issue now.
