### ISSUE TITLE
feature reqest nginx reverse proxy manager would love thank you

### ISSUE THREAD

**Issue by Oaf2776** [guldkage/Pterodactyl-Installer#9]
Please add nginx reverse proxy manager thank you

**Comment by guldkage** [comment]
Hello

Sorry for the late reply. Can you elaborate on how the NGINX Reverse Proxy Manager should be integrated after what you have in mind?
Thanks

**Comment by Oaf2776** [comment]
during the install process of pterodactyl panel maybe

**Comment by guldkage** [comment]
Hello again,

Sorry for the late reply again.

At the moment, unfortunately, there will be no support for NGINX Proxy Manager, as I do not have knowledge in it, and do not have time to look into it.
If you need help setting up NGINX Proxy Manager, I may be able to help you. If so, you can contact me on Discord: guldkage.

Have a good day and thanks for the suggestion :)

**Comment by Oaf2776** [comment]
ok thank you
